version: "3.8"

services:
  db:
    image: postgres
    container_name: database
    restart: always
    networks:
      - app-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
networks:
  app-network:
    name: app-network
